Branching ratio
npeard/mmwave-calc pull request #8
Opened 2024-06-11 21:57 UTC by npeard

Wrote function to calculate the probable cascade path for a Cs atom from arbitrary input source state to a target state (usually the ground state).

2024-07-25 22:07 UTC, neutrinonerd3333 requested changes
Never thought I'd see graph algorithms come up in physics grad school! Summary of review comments, in order of urgency:
- Some correctness issues with the shortest/most-probably path computation.
- Documention: more descriptive variable names + strategically placed docstrings in functions with nontrivial logic would be super helpful for readability.
- Miscellaneous style suggestions

2024-07-25 22:07 UTC, neutrinonerd3333 commented on models/rydberg_calcs.py
> +    def get_shortest_decay(self, source=None, target=None):
This function would specifically benefit from a docstring explaining behavior. (And tests, at least of the core shortest-paths computation logic, but that's a bigger time investment that I'm not going to insist on.)

2024-08-06 20:17 UTC, npeard commented on models/rydberg_calcs.py
> +                                        decay_path])
The decay rate is related to the transition probability, therefore the shortest time path should also be the most probable.

2024-08-08 01:10 UTC, neutrinonerd3333 commented on models/rydberg_calcs.py
> +                                        decay_path])
I think this is a counterexample (values are decay rates $\Gamma$): decay through the metastable state is most likely but slower.

```
initial───────┐     
   │          │     
   │          │     
   │         (2)    
   │          │     
  (1)         ▼     
   │      metastable
   │          │     
   │          │     
   ├──(0.01)──┘     
   │                
   ▼                
ground              
```

2025-03-31 20:06 UTC, closed without merging